Repository sorbet/sorbet, pull requests merged in 2019-12, with the labels that each got.

#2292 Revert "Introduce release file for java platform (#2254)"
  .buildkite/build-static-release-java.sh
  .buildkite/pipeline.yaml
  .buildkite/publish-ruby-gems.sh
Labels: mergify

#2298 Add build-static-release-java.sh to generate Java platform gem
  .buildkite/build-static-release-java.sh
  .buildkite/pipeline.yaml
  .buildkite/publish-ruby-gems.sh
Labels: mergify

#2305 Fix publish-ruby-gems.sh
  .buildkite/publish-ruby-gems.sh
Labels: mergify

#2304 IDE: Cleaner LSPTypechecker::retypecheck() interface.
  main/lsp/LSPTypechecker.cc
  main/lsp/LSPTypechecker.h
  main/lsp/requests/code_action.cc
Labels: IDE

#2313 IDE: Cancel the correct timer when merging updates.
  main/lsp/LSPPreprocessor.cc
Labels: IDE

#2310 Use RealStdlib for method method in gem generator
  gems/sorbet/lib/gem-generator-tracepoint/tracepoint_serializer.rb
  gems/sorbet/lib/real_stdlib.rb
  gems/sorbet/test/hidden-method-finder/simple/ruby_2_4_3_hidden.rbi.exp
  gems/sorbet/test/hidden-method-finder/simple/ruby_2_6_3_hidden.rbi.exp
  gems/sorbet/test/hidden-method-finder/thorough/ruby_2_4_3_hidden.rbi.exp
  gems/sorbet/test/hidden-method-finder/thorough/ruby_2_6_3_hidden.rbi.exp
  gems/sorbet/test/snapshot/partial/local_gem/expected/sorbet/rbi/gems/my_gem.rbi
  gems/sorbet/test/snapshot/partial/local_gem/gems/0.0.0/gems/my_gem-0.0.0/lib/my_gem.rb
Labels: waiting on author

#2350 Initial pass at attached_class docs
  website/docs/attached-class.md
  website/sidebars.json
Labels: mergify

#2357 Revert "keep `include` and `extend` in the tree (#2332)"
  ast/Helpers.cc
  main/autogen/autogen.cc
  namer/namer.cc
  rbi/core/kernel.rbi
  test/test_corpus.cc
  test/testdata/cfg/array.rb.cfg.exp
  test/testdata/cfg/break.rb.cfg.exp
  test/testdata/desugar/sclass.rb.flatten-tree.exp
  test/testdata/desugar/sclass_inheritance.rb.flatten-tree.exp
  test/testdata/infer/control_flow/simple.rb.cfg.exp
  test/testdata/infer/isa_generic.rb.cfg.exp
  test/testdata/infer/rebind.rb.cfg.exp
  test/testdata/infer/self_type.rb.cfg.exp
  test/testdata/infer/transitive.rb.cfg.exp
  test/testdata/namer/ancestors.rb.flatten-tree.exp
  test/testdata/namer/module_function.rb.cfg.exp
  test/testdata/namer/redefinition_method.rb.flatten-tree.exp
  test/testdata/namer/simple.rb
  test/testdata/namer/simple.rb.flatten-tree.exp
  test/testdata/namer/simple.rb.symbol-table-raw.exp
  test/testdata/resolver/ancestor_scope.rb.flatten-tree.exp
  test/testdata/resolver/class_instance_vars.rb.flatten-tree.exp
  test/testdata/resolver/fuzz_ancester.rb
  test/testdata/resolver/fuzz_include_type_alias.rb
  test/testdata/resolver/optional_nil.rb.flatten-tree.exp
  test/testdata/resolver/optional_nil.rb.name-tree.exp
  test/testdata/rewriter/attr.rb.flatten-tree.exp
Labels: mergify

#2355 Add LSP epochs to core::File (currently unused).
  core/Files.cc
  core/Files.h
  main/lsp/LSPPreprocessor.cc
  main/lsp/TimeTravelingGlobalState.cc
  main/lsp/test/lsp_preprocessor_test.cc
Labels: IDE

#2356 Clean up control flow of GlobalState::tryCommitEpoch.
  core/GlobalState.cc
Labels: IDE

#2360 LSP: Change interface of typechecking methods.
  main/lsp/LSPTypechecker.cc
  main/lsp/LSPTypechecker.h
Labels: IDE

#2363 LSP: Move text preprocessing functionality into helper functions.
  main/lsp/LSPPreprocessor.cc
  main/lsp/json_types.cc
  main/lsp/tools/make_lsp_types.cc
Labels: IDE

#2361 Use tasks in LSPTypecheckerCoordinator.
  core/lsp/Task.h
  main/lsp/LSPTypecheckerCoordinator.cc
  main/lsp/LSPTypecheckerCoordinator.h
Labels: IDE

#2389 LSP: Delurk WorkerPool from config + abstract away multithreading
  main/lsp/LSPConfiguration.cc
  main/lsp/LSPConfiguration.h
  main/lsp/LSPPreprocessor.cc
  main/lsp/LSPPreprocessor.h
  main/lsp/LSPTypechecker.cc
  main/lsp/LSPTypechecker.h
  main/lsp/LSPTypecheckerCoordinator.cc
  main/lsp/LSPTypecheckerCoordinator.h
  main/lsp/TimeTravelingGlobalState.cc
  main/lsp/TimeTravelingGlobalState.h
  main/lsp/lsp.cc
  main/lsp/lsp.h
  main/lsp/request_dispatch.cc
  main/lsp/requests/code_action.cc
  main/lsp/requests/completion.cc
  main/lsp/requests/definition.cc
  main/lsp/requests/document_highlight.cc
  main/lsp/requests/document_symbol.cc
  main/lsp/requests/hover.cc
  main/lsp/requests/references.cc
  main/lsp/requests/signature_help.cc
  main/lsp/requests/type_definition.cc
  main/lsp/requests/workspace_symbols.cc
  main/lsp/test/lsp_preprocessor_test.cc
  main/lsp/wrapper.cc
  main/realmain.cc
Labels: IDE
